### PR TITLE
Add invoice language

### PR DESCRIPTION
**Pull request by LarsK1**
This adds a field for an alternating invoice language

### CODE REVIEW

**Comment by LarsK1** [comment]
@hillelcoren one bug is remaing, dart issues an error about the missing string "invoicelanguage" even though it's defined in i18n.dart? Any idea?

**Comment by hillelcoren** [comment]
Not sure I understand this PR, the client's language determines the invoice language.

**Comment by LarsK1** [comment]
Sorry for my late reply. In most European countries the tax offices only accept invoices in the countries language. Therefore when this setting is set to a different country the invoice should be added to the PDF in the second language. (to be done)

**Comment by hillelcoren** [comment]
The app already supports assigning a language directly to the client

**Pull request closed without merging**
